- hosts: localhost
  vars_files:
     - /root/Ansible/Wizall_Prod/ML/var.yml
  tasks:
#     - command:
#          cmd: "git pull"
#          chdir: "/root/Ansible/Wizall_Prod/ML/MFS-WizallMW/"
#       register: output

     - debug:
          msg: "{{ output }}"
       
     - name: "MVN running on MobifinMainModule"
       command:
          cmd: "mvn clean install"
          chdir: "/root/Ansible/Wizall_Prod/ML/MFS-WizallMW/MobifinMainModule"

     - name: "MVN running on RedisDataProvider"
       command:
          cmd: "mvn clean install"
          chdir: "/root/Ansible/Wizall_Prod/ML/MFS-WizallMW/RedisDataProvider"

     - name: "MVN running on DatabaseServiceProvider"
       command:
          cmd: "mvn clean install"
          chdir: "/root/Ansible/Wizall_Prod/ML/MFS-WizallMW/DatabaseServiceProvider"

     - name: "MVN running on TransactionModule"
       command:
          cmd: "mvn clean install"
          chdir: "/root/Ansible/Wizall_Prod/ML/MFS-WizallMW/TransactionModule"

     - name: "MVN running on {{ service }}"
       command:
          cmd: "mvn clean install"
          chdir: "/root/Ansible/Wizall_Prod/ML/MFS-WizallMW/{{ service }}"
